title: Sample OAD Process

# List of folder paths where user added custom registered OpenMDAO components
module_folders: '../../modules'

# Input and output files
input_file: ./problem_inputs_BWB_sweep35.xml
output_file: ./problem_outputs_BWB_sweep35.xml

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver: om.ScipyOptimizeDriver(tol=1e-2, optimizer='COBYLA')

# Definition of OpenMDAO model
# Although "model" is a mandatory name for the top level of the model, its
# sub-components can be freely named by user
model:

  #  Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
  nonlinear_solver: om.NonlinearBlockGS(maxiter=100, atol=1e-2)
  linear_solver: om.DirectSolver()


  # Components can be put in sub-groups
  subgroup:

    # A group can be set with its own solvers.
    # Uncomment the 2 next lines for using the performance module with "mission_file_path: ::sizing_mission"
    nonlinear_solver: om.NonlinearBlockGS(maxiter=100, atol=1e-2, iprint=0)
    linear_solver: om.DirectSolver()

    geometry:
      id: fastoad.geometry.test.2
    weight:
      id: fastoad.weight.BWBtest.1
    mtow:
      id: fastoad.mass_performances.compute_MTOW
    #mtow:
      #id: fastoad.mass_performances.compute_MTOW.BWB
    hq_static_margin:
      id: fastoad.handling_qualities.static_margin.TEST
    ComputeWingPositionBWB:
      id: bwb.loop.wing_position
    aerodynamics_highspeed:
      id: aerodinamica.highspeed.2
    aerodynamics_lowspeed:
      id: aerodinamica.lowspeed.2
    aerodynamics_takeoff:
      id: aerodynamics.takeoff.2
    aerodynamics_landing:
      id: aerodinamica.landing.2
      use_xfoil: false
  performance:
    id: fastoad.performances.mission
    propulsion_id: fastoad.wrapper.propulsion.rubber_engine
    #mission_file_path: ::sizing_breguet
    # mission_file_path: ::sizing_mission  # Activate solvers in "subgroup" if you use this line.
    mission_file_path: ./bwb_missions.yml
    mission_name: sizing
    out_file: ./flight_points.csv
    adjust_fuel: true
    is_sizing: true
  #ComputeWingAreaBWB:
    #id: fastoad.loop.wing_area.bwb
  ComputeWingArea:
    id: fastoad.loop.wing_area.2


#optimization: # This section is needed only if optimization process is run
  #design_variables:
    #- name: data:geometry:wing:aspect_ratio
      #lower: 0.5 # 3.0 - Changed the value from 3 to 0.5, because BWB AR is much lower
      #upper: 18.0
  #constraints:
    #- name: data:geometry:wing:span
      #upper: 60.0
  #objective:
    #- name: data:mission:sizing:needed_block_fuel
      #scaler: 1.e-4
